#!/usr/bin/env bash
# clean up files generated by a persistent latex document builder
# such as in the texstudio package for vs-code
# aux toc lof log lot out pdf
TEXTEMPDIR="/tmp/tex-build-dump"
mkdir -p "$TEXTEMPDIR"
if [ $# -ge 1 ]; then
  for d in "${@}"; do
    for f in aux toc lof log lot out nlo ; do
      find "$d" -type f -name "*.$f" -exec mv -t "$TEXTEMPDIR" {} \;
    done
  done
else
  for f in aux toc lof log lot out nlo ; do
    find . -type f -name "*.$f" -exec mv -t "$TEXTEMPDIR" {} \;
  done
fi

